version: "3.3"  # optional since v1.27.0
services:
  flask_app:
    restart: always
    build: './flask_app'
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    expose:
      - "5000"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/idea_data
    expose:
      - "5432"

volumes:
  db:
    driver: local