version: "3.3"  # optional since v1.27.0
services:
  #ubuntu:
  #  image: ubuntu
  #  restart: on-failure
  #  command: ["sleep","infinity"]
  #  networks:
  #    - prova

  flask_app:
    build: './flask_app'
    ports:
      - "5001:5000"
    depends_on:
      - elasticsearch
    restart: always
    expose:
      - "5001"

  consumer:
    build: './consumer'
    depends_on:
      - flask_app
    restart: always

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
